### ISSUE TITLE
配置时设置了size 20M，但上传时提示不能超过1M的前端验证。

### ISSUE THREAD

**Issue by xiongbao** [imlinhanchao/coding-picbed-api#3]
`if (file.size > 1024 * 1024) {
                            this.images.splice(i, 1);
                            this.error = '文件太大了！请选择小于 1 MB 的图片';
                            return;
                        }`

这里要调用config.json里的参数比对才是。

**Comment by imlinhanchao** [comment]
```
if (config.size > 0 && files.f.size > 1024 * 1024 * config.size) {
```
https://github.com/imlinhanchao/coding-picbed-api/blob/master/index.js#L64

你可能需要更新一下代码，这个问题之前已经修复的了。

**Comment by imlinhanchao** [comment]
噢，突然发现你是说 `upload.html`，那个只是个调用范例噢。请按照自己的实际需求开发调用界面。
