### ISSUE TITLE
上传图片提示：Invalid repository URL!

### ISSUE THREAD

**Issue by grofis** [imlinhanchao/coding-picbed-api#4]
我通过你给的这个地址：http://picbed.librejo.cn/上传图片
配置了令牌，项目公布公开都提示以上的问题。

是coding的API改过了吗？还是怎么回事...

**Comment by imlinhanchao** [comment]
確認仍然可用。請問是在個人設置的訪問令牌申請的令牌嗎？請參考[這裏](https://github.com/imlinhanchao/coding-picbed#%E5%87%86%E5%A4%87)申請令牌。

**Comment by grofis** [comment]
![](http://lrhxrw.coding-pages.com/BCdsf2addTYU89i.jpg)  看这个图片吧

**Comment by grofis** [comment]
http://lrhxrw.coding-pages.com/BCdsf2addTYU89i.jpg

**Comment by imlinhanchao** [comment]
OK，我理解你的問題了。你應該是要填寫倉庫的 Web URL，比如：https://username.coding.net/p/project/d/repository/git

**Comment by imlinhanchao** [comment]
请问问题是否已解决？
